#!/usr/bin/env python3
from subprocess import run
import re

ICONS = ("󰸈", "󰕿", "󰖀", "󰕾")

# get volume info from amixer
output = str(
    run(["amixer", "-D", "pulse", "sget", "Master"], capture_output=True).stdout,
    "utf-8",
)


def get_volume_perc():
    # filter out percent from output
    global output
    perc = int(re.search("\d{1,3}(?=%)", output).group())
    return perc


def get_volume_muted():
    # filter out mute state from output
    global output
    mute = re.search("\[off\]", output)
    if mute:
        return True
    return False


def get_volume_icon():
    perc = get_volume_perc()
    if get_volume_muted() == True:
        return ICONS[0]
    elif perc >= 60:
        return ICONS[3]
    elif perc >= 30:
        return ICONS[2]
    else:
        return ICONS[1]


print(f"{get_volume_icon()} {get_volume_perc()}%")
